/* ============================================================
   ANEST IWATA VIETNAM — Nhóm Phụ Kiện & Quà Lưu Niệm (Team Iwata Gear)
   Nguồn: https://www.teamiwata.com/collections/all (20 sản phẩm — đã loại 1 sản phẩm
   placeholder "Vacuum Pump" chứa nội dung Lorem ipsum/test, không phải dữ liệu thật)
   Giá gốc tính bằng USD, quy đổi tham khảo ~25.000 VNĐ/USD, ghi rõ "giá tham khảo".
   ============================================================ */
(function () {
  var list = [
    {
      slug: "gear-work-shirt",
      name: "Áo Sơ Mi Bảo Hộ Anest Iwata (Work Shirt)",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/products/workshirt_large.jpg?v=1646670143",
      shortDesc: "Áo sơ mi bảo hộ Red Kap chống nhăn, công nghệ Touchtex thấm hút mồ hôi, logo Anest Iwata ngực trước.",
      lead: "Áo sơ mi bảo hộ công nghiệp Red Kap cổ điển, chất liệu chống nhăn với công nghệ Touchtex™ giúp thấm hút mồ hôi và giữ màu bền theo thời gian — một item quen thuộc của người thợ trong ngành sơn.",
      features: [["🧵", "Vải Poplin 4,25oz — 65% Polyester / 35% Cotton"], ["💧", "Công nghệ Touchtex™ thấm hút, chống bám bẩn"], ["🏷️", "Logo Anest Iwata thêu ngực trước"], ["📏", "Đủ size từ S đến 4XL"]],
      specs: { "Chất liệu": "65% Polyester / 35% Cotton, 4.25oz Poplin", "Kiểu in/thêu": "Logo Anest Iwata ngực trước", "Giá tham khảo (nguồn Mỹ)": "$35" },
      applications: ["Đồng phục xưởng sơn", "Quà tặng đối tác, đại lý"],
      why: "Chất liệu Touchtex bền màu, thấm hút tốt phù hợp mặc cả ngày dài trong xưởng — không chỉ là món đồ lưu niệm mà còn dùng được như bảo hộ lao động thực tế."
    },
    {
      slug: "gear-long-sleeve-tee",
      name: "Áo Thun Dài Tay Logo Anest Iwata",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/products/AILongSleeve_1_large.jpg?v=1647894779",
      shortDesc: "Áo thun dài tay cổ điển, logo nhỏ ngực trái, chữ Anest Iwata dọc tay áo trái.",
      lead: "Mẫu áo thun dài tay kinh điển với logo Anest Iwata nhỏ gọn ở ngực trái và dòng chữ \"Anest Iwata\" in dọc theo tay áo trái, chất liệu cotton pha DryBlend thoáng mát.",
      features: [["🧵", "50% Cotton / 50% DryBlend Polyester Jersey"], ["🏷️", "Logo ngực trái + chữ dọc tay áo trái"], ["📏", "Đủ size từ S đến 4X"]],
      specs: { "Chất liệu": "50% Cotton / 50% DryBlend Polyester", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Trang phục đi sự kiện, hội chợ ngành sơn", "Quà tặng khách hàng thân thiết"],
      why: "Thiết kế tối giản, dễ phối đồ hằng ngày — phù hợp làm quà tặng đại lý hoặc trang phục đại diện thương hiệu tại các sự kiện ngành."
    },
    {
      slug: "gear-blue-nozzle-tee",
      name: "Áo Thun Blue Nozzle - Phiên Bản Đặc Biệt",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/products/BlueNozzle_large.png?v=1646949039",
      shortDesc: "Áo thun phiên bản đặc biệt, hình đầu vòi phun (nozzle) và khẩu hiệu thương hiệu in ngực trước.",
      lead: "Anest Iwata là nơi hội tụ của đam mê, sáng tạo và đổi mới — mẫu áo thun xanh nổi bật này in hình đầu vòi phun cùng khẩu hiệu thương hiệu ở ngực trước, kèm dòng chữ ANEST IWATA in dọc phía dưới bên phải.",
      features: [["🧵", "100% Cotton Jersey"], ["🎨", "Hình đầu vòi phun (nozzle) in ngực trước"], ["🏷️", "Chữ ANEST IWATA in dọc phía dưới bên phải"]],
      specs: { "Chất liệu": "100% Cotton Jersey", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Trang phục sự kiện, triển lãm"],
      why: "Thiết kế đồ hoạ nổi bật giúp món đồ này trở thành vật phẩm sưu tầm được yêu thích trong cộng đồng người dùng Anest Iwata."
    },
    {
      slug: "gear-spray-gun-tee",
      name: "Áo Thun Spray Gun - Phiên Bản Đặc Biệt SEMA 2021",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/products/Picture4_large.png?v=1647894197",
      shortDesc: "Áo thun đen phiên bản giới hạn, thiết kế riêng cho triển lãm SEMA 2021, số lượng có hạn.",
      lead: "Mẫu áo thun đen độc nhất được thiết kế riêng cho triển lãm SEMA 2021 — phiên bản giới hạn, số lượng có hạn, in logo Anest Iwata ngực trái cùng hoạ tiết đồ hoạ riêng của sự kiện.",
      features: [["🧵", "100% Cotton Jersey"], ["🏆", "Thiết kế riêng cho SEMA 2021"], ["🎨", "Logo ngực trái + đồ hoạ riêng theo chủ đề sự kiện"]],
      specs: { "Chất liệu": "100% Cotton Jersey", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Vật phẩm sưu tầm cho người hâm mộ thương hiệu"],
      why: "Là phiên bản giới hạn gắn liền với một sự kiện cụ thể (SEMA 2021), đây là món đồ có giá trị sưu tầm hơn hẳn các mẫu áo thông thường."
    },
    {
      slug: "gear-series2-parts-shirt",
      name: "Áo Thun Series 2 Parts",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/products/MicrosoftTeams-image_3_compact.jpg?v=1774031226",
      shortDesc: "Áo thun xanh in hình cấu tạo chi tiết súng Series 2 mặt sau, logo Anest Iwata mặt trước.",
      lead: "Mẫu áo thun xanh với logo Anest Iwata ở mặt trước và hình vẽ cấu tạo chi tiết (exploded view) của dòng súng Series 2 mới ở mặt sau — dành cho những ai yêu thích kỹ thuật cơ khí đằng sau sản phẩm.",
      features: [["🎨", "Hình cấu tạo chi tiết súng Series 2 in mặt sau"], ["🏷️", "Logo Anest Iwata mặt trước"]],
      specs: { "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Quà tặng cho kỹ thuật viên, người yêu thích cơ khí súng phun"],
      why: "Hình in cấu tạo chi tiết súng phun là điểm nhấn thú vị, phù hợp với khách hàng am hiểu kỹ thuật của dòng Series 2."
    },
    {
      slug: "gear-mystery-tshirt",
      name: "Áo Thun Bí Ẩn (Mystery T-Shirt)",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/Untitleddesign_large.png?v=1713983237",
      shortDesc: "Chọn size, nhận ngẫu nhiên một mẫu áo thun Anest Iwata bất kỳ trong kho — giá ưu đãi.",
      lead: "Một lựa chọn thú vị dành cho ai muốn thử vận may: chọn size mong muốn và nhận về một mẫu áo thun Anest Iwata ngẫu nhiên từ kho hàng, với mức giá ưu đãi hơn nhiều so với mua lẻ từng mẫu.",
      features: [["🧵", "100% Cotton Jersey"], ["🎲", "Nhận ngẫu nhiên một mẫu áo bất kỳ trong kho"], ["💰", "Giá ưu đãi hơn mua lẻ"]],
      specs: { "Chất liệu": "100% Cotton Jersey", "Giá tham khảo (nguồn Mỹ)": "$15" },
      applications: ["Quà tặng bất ngờ, chương trình khuyến mãi nội bộ"],
      why: "Mức giá ưu đãi kèm yếu tố bất ngờ khiến đây là lựa chọn phù hợp cho các chương trình minigame, quà tặng tri ân khách hàng."
    },
    {
      slug: "gear-logo-shirt-black",
      name: "Áo Thun Logo Anest Iwata - Đen",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/Shirt_AIUSLogoHorizontal_large.jpg?v=1753459316",
      shortDesc: "Áo thun đen, logo ngực trái, khẩu hiệu thương hiệu in ngang lưng áo.",
      lead: "Mẫu áo thun đen với logo Anest Iwata ở ngực trái và khẩu hiệu thương hiệu in ngang phía sau lưng áo — thiết kế tối giản, dễ phối đồ hằng ngày.",
      features: [["🧵", "100% Cotton Jersey"], ["🏷️", "Logo ngực trái"], ["🎨", "Khẩu hiệu thương hiệu in ngang lưng áo"]],
      specs: { "Chất liệu": "100% Cotton Jersey", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Trang phục hằng ngày cho nhân viên, đại lý"],
      why: "Màu đen trung tính dễ phối đồ, phù hợp làm đồng phục sự kiện hoặc quà tặng phổ thông cho nhiều đối tượng khách hàng."
    },
    {
      slug: "gear-series2-ws400-shirt",
      name: "Áo Thun Series 2 WS-400 - Xanh",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/Untitled_Artwork_large.png?v=1753459448",
      shortDesc: "Áo thun xanh in hình súng phun WS-400 Series 2 — dòng súng chủ lực — mặt sau.",
      lead: "Mẫu áo thun xanh nổi bật với logo Anest Iwata mặt trước và hình ảnh súng phun WS-400 Series 2 — dòng súng phun sơn bóng chủ lực — in mặt sau, dành cho người hâm mộ dòng sản phẩm này.",
      features: [["🎨", "Hình súng WS-400 in mặt sau"], ["🏷️", "Logo Anest Iwata ngực trái"]],
      specs: { "Chất liệu": "100% Cotton Jersey", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Quà tặng cho khách hàng dùng dòng WS-400"],
      why: "Là món quà phù hợp cho khách hàng đang sử dụng chính dòng súng WS-400 Series 2, tạo sự gắn kết thương hiệu — sản phẩm."
    },
    {
      slug: "gear-series2-auto-shirt",
      name: "Áo Thun Series 2 Auto - Đen",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/Untitleddesign_1e80d160-c1cb-4c28-ad90-00cbdbb15bc3_large.png?v=1753459705",
      shortDesc: "Áo thun đen, hoạ tiết ô tô hoàn toàn mới in mặt sau, logo Anest Iwata mặt trước.",
      lead: "Mẫu áo thun đen với logo Anest Iwata mặt trước và hoạ tiết ô tô hoàn toàn mới in mặt sau — dành cho những ai đam mê dòng sản phẩm sơn sửa chữa ô tô của Anest Iwata.",
      features: [["🎨", "Hoạ tiết ô tô mới in mặt sau"], ["🏷️", "Logo Anest Iwata mặt trước"]],
      specs: { "Chất liệu": "100% Cotton Jersey", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Quà tặng cho khách hàng ngành sơn sửa chữa ô tô"],
      why: "Hoạ tiết ô tô là điểm nhấn phù hợp riêng cho nhóm khách hàng gara, xưởng dịch vụ sơn sửa chữa ô tô."
    },
    {
      slug: "gear-iwatastein-shirt",
      name: "Áo Thun Iwatastein - Xanh Lá - Phiên Bản Đặc Biệt",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/Shirt_Iwatastein_large.jpg?v=1753459870",
      shortDesc: "Áo thun xanh lá, thiết kế Iwatastein độc quyền do hoạ sĩ Craig Fraser sáng tạo cho SEMA '24.",
      lead: "Mẫu áo thun xanh lá nổi bật với logo và hình vẽ Iwatastein phiên bản đặc biệt, được sáng tạo bởi hoạ sĩ Craig Fraser dành riêng cho triển lãm SEMA 2024.",
      features: [["🧵", "100% Cotton Jersey"], ["🎨", "Thiết kế Iwatastein độc quyền bởi Craig Fraser"], ["🏆", "Phiên bản đặc biệt SEMA '24"]],
      specs: { "Chất liệu": "100% Cotton Jersey", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Vật phẩm sưu tầm cho người hâm mộ thương hiệu"],
      why: "Sự hợp tác với hoạ sĩ khách mời Craig Fraser khiến mẫu áo này có giá trị nghệ thuật và sưu tầm riêng biệt so với các mẫu áo tiêu chuẩn."
    },
    {
      slug: "gear-artist-series-hat",
      name: "Mũ Artist Series - Thiết Kế Bởi Craig Fraser",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/CraigFraserHat1_large.png?v=1761747180",
      shortDesc: "Mũ phiên bản đặc biệt Artist Series, mặt dưới lưỡi trai thiết kế bởi hoạ sĩ Craig Fraser.",
      lead: "Mũ Anest Iwata phiên bản Artist Series đặc biệt với mặt dưới lưỡi trai được thiết kế riêng bởi hoạ sĩ Craig Fraser — số lượng có hạn.",
      features: [["🎨", "Mặt dưới lưỡi trai thiết kế bởi Craig Fraser"], ["🔢", "Số lượng có hạn"]],
      specs: { "Giá tham khảo (nguồn Mỹ)": "$35" },
      applications: ["Vật phẩm sưu tầm, quà tặng cao cấp"],
      why: "Số lượng giới hạn cùng thiết kế nghệ sĩ khách mời khiến mũ Artist Series trở thành món quà đáng chú ý cho khách hàng VIP."
    },
    {
      slug: "gear-100th-anniversary-hat",
      name: "Mũ Kỷ Niệm 100 Năm - Thiết Kế Bởi BuckWild",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/100YearHat-MAIN_large.jpg?v=1785178461",
      shortDesc: "Mũ snapback vành phẳng kỷ niệm 100 năm thành lập Anest Iwata, thiết kế bởi hoạ sĩ BuckWild.",
      lead: "Mũ snapback vành phẳng phiên bản đặc biệt kỷ niệm 100 năm thành lập Anest Iwata, được thiết kế bởi hoạ sĩ BuckWild — một cột mốc đáng nhớ của thương hiệu.",
      features: [["🏆", "Kỷ niệm 100 năm thành lập thương hiệu"], ["🎨", "Thiết kế bởi hoạ sĩ BuckWild"], ["🧢", "Kiểu snapback, vành phẳng"]],
      specs: { "Kiểu mũ": "Snapback, vành phẳng", "Giá tham khảo (nguồn Mỹ)": "$45" },
      applications: ["Quà tặng kỷ niệm, vật phẩm sưu tầm"],
      why: "Gắn liền với cột mốc 100 năm thành lập, đây là món quà mang ý nghĩa lịch sử thương hiệu đặc biệt hơn các sản phẩm quà tặng thông thường."
    },
    {
      slug: "gear-hat-two-pack",
      name: "Bộ Đôi Mũ Đặc Biệt - Craig Fraser & BuckWild",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "apparel", subCatLabel: "Trang phục",
      img: "https://www.teamiwata.com/cdn/shop/files/2_large.png?v=1785959477",
      shortDesc: "Combo 2 mũ phiên bản đặc biệt: Artist Series (Craig Fraser) và Kỷ niệm 100 năm (BuckWild).",
      lead: "Combo gồm 2 chiếc mũ phiên bản đặc biệt trong một: mũ Artist Series do Craig Fraser thiết kế và mũ Kỷ niệm 100 năm do BuckWild thiết kế — dành cho người sưu tầm muốn có trọn bộ.",
      features: [["🧢", "Gồm 2 mũ: Artist Series + Kỷ niệm 100 năm"], ["🎨", "Thiết kế bởi Craig Fraser và BuckWild"]],
      specs: { "Số lượng": "Combo 2 mũ", "Giá tham khảo (nguồn Mỹ)": "$60" },
      applications: ["Quà tặng combo cho khách hàng VIP, đại lý lớn"],
      why: "Mua combo tiết kiệm hơn mua lẻ từng mũ, phù hợp làm phần thưởng hoặc quà tặng cao cấp cho các chương trình tri ân lớn."
    },
    {
      slug: "gear-100th-sticker-pack",
      name: "Bộ Sticker Kỷ Niệm 100 Năm",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "cool-stuff", subCatLabel: "Đồ lưu niệm",
      img: "https://www.teamiwata.com/cdn/shop/files/100YearStickers_All_large.jpg?v=1785247488",
      shortDesc: "Bộ 6 sticker từ bộ sưu tập kỷ niệm 100 năm Anest Iwata, dán tủ đồ, laptop, xe, dụng cụ.",
      lead: "Bộ sưu tập gồm 6 sticker từ dòng kỷ niệm 100 năm Anest Iwata, phù hợp trang trí tủ đồ nghề, laptop, xe hơi hay bất cứ vật dụng nào bạn muốn thể hiện tinh thần thương hiệu.",
      features: [["🔢", "Bộ gồm 6 sticker"], ["🏆", "Thuộc dòng kỷ niệm 100 năm"]],
      specs: { "Số lượng": "6 sticker/bộ", "Giá tham khảo (nguồn Mỹ)": "$20" },
      applications: ["Trang trí dụng cụ, tủ đồ nghề, laptop, xe"],
      why: "Giá rẻ, dễ mua làm quà tặng nhỏ kèm đơn hàng thiết bị, tạo thiện cảm với khách hàng mà không tốn nhiều chi phí."
    },
    {
      slug: "gear-2025-sticker-pack",
      name: "Bộ Sticker 2025",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "cool-stuff", subCatLabel: "Đồ lưu niệm",
      img: "https://www.teamiwata.com/cdn/shop/files/Sticker_Pack_2024_large.jpg?v=1718122783",
      shortDesc: "Bộ 4 sticker ngẫu nhiên từ bộ sưu tập Anest Iwata, dán tủ đồ, laptop, xe, dụng cụ.",
      lead: "Bộ sưu tập gồm 4 sticker ngẫu nhiên từ bộ sưu tập Anest Iwata, phù hợp trang trí tủ đồ nghề, laptop, xe hơi hay bất cứ vật dụng nào bạn muốn thể hiện tinh thần thương hiệu.",
      features: [["🔢", "Bộ gồm 4 sticker, chọn ngẫu nhiên"]],
      specs: { "Số lượng": "4 sticker/bộ (ngẫu nhiên)", "Giá tham khảo (nguồn Mỹ)": "$20" },
      applications: ["Trang trí dụng cụ, tủ đồ nghề, laptop, xe"],
      why: "Yếu tố ngẫu nhiên tạo sự thú vị, phù hợp làm quà tặng nhỏ kèm đơn hàng hoặc chương trình khuyến mãi."
    },
    {
      slug: "gear-mil-gauge",
      name: "Thước Đo Độ Dày Lớp Sơn Ướt (Mil Gauge)",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "tools", subCatLabel: "Dụng cụ",
      img: "https://www.teamiwata.com/cdn/shop/products/MILGage_large.png?v=1650557380",
      shortDesc: "Thước đo độ dày màng sơn ướt (Wet Film Gauge) in logo Anest Iwata, dụng cụ kiểm tra nhanh, giá rẻ.",
      lead: "Thước đo độ dày màng sơn ướt (Wet Film Gauge) in logo Anest Iwata riêng, giúp thợ sơn kiểm tra nhanh độ dày lớp sơn vừa phun ngay tại hiện trường — một dụng cụ nhỏ nhưng hữu ích hằng ngày.",
      features: [["📏", "Đo nhanh độ dày lớp sơn ướt tại hiện trường"], ["🏷️", "In logo Anest Iwata riêng"]],
      specs: { "Công dụng": "Đo độ dày màng sơn ướt (Wet Film Gauge)", "Giá tham khảo (nguồn Mỹ)": "$3" },
      applications: ["Kiểm tra độ dày lớp sơn khi phun", "Đào tạo kỹ thuật viên sơn mới"],
      why: "Giá rất rẻ nhưng là dụng cụ thực dụng mà bất kỳ thợ sơn nào cũng nên có sẵn trong túi đồ nghề để kiểm soát chất lượng lớp sơn ngay khi thi công."
    },
    {
      slug: "gear-ffs-adaptor",
      name: "Đầu Chuyển FFS Cho Súng Anest Iwata",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "ffs-adaptors", subCatLabel: "Đầu chuyển cốc FFS",
      img: "https://www.teamiwata.com/cdn/shop/files/FFS_Adapter_27520_I-10_large.jpg?v=1753370611",
      shortDesc: "Đầu chuyển thay thế cho súng phun Anest Iwata dùng hệ cốc FFS, nhiều mã tương thích (I-1, I-10, I-12...).",
      lead: "Đầu chuyển (adaptor) thay thế dành cho súng phun Anest Iwata sử dụng hệ thống cốc FFS (Fast Flow System), có nhiều mã tương thích khác nhau (I-1, I-10, I-12, I-13, I-20, I-40) theo từng dòng súng cụ thể.",
      features: [["🔗", "Nhiều mã tương thích: I-1, I-10, I-12, I-13, I-20, I-40"], ["♻️", "Phụ kiện thay thế chính hãng cho hệ cốc FFS"]],
      specs: { "Loại phụ kiện": "Đầu chuyển (adaptor) hệ cốc FFS", "Mã tương thích": "I-1 / I-10 / I-12 / I-13 / I-20 / I-40", "Giá tham khảo (nguồn Mỹ)": "$30" },
      applications: ["Thay thế đầu chuyển FFS bị hỏng/mất", "Trang bị thêm cho súng dùng hệ cốc FFS"],
      why: "Cần chọn đúng mã đầu chuyển tương ứng với dòng súng đang sử dụng — nên đối chiếu bảng tương thích của Anest Iwata trước khi đặt hàng."
    },
    {
      slug: "gear-spray-suit",
      name: "Bộ Đồ Bảo Hộ Phun Sơn Cao Cấp (Micro-Fabric)",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "tools", subCatLabel: "Dụng cụ",
      img: "https://www.teamiwata.com/cdn/shop/products/AIUSSpraySuit-A1_large.jpg?v=1592930409",
      shortDesc: "Bộ đồ bảo hộ vải vi sợi, chống tĩnh điện, chắn dung môi và bụi sơn, nhẹ và thoáng khí.",
      lead: "Bộ đồ bảo hộ phun sơn cao cấp Anest Iwata làm từ vải vi sợi phủ lớp bảo vệ, tạo hàng rào chống lại dung môi và bụi sơn nhưng vẫn nhẹ, thoáng khí — phù hợp mặc cả những ngày làm việc nóng bức. Đạt chuẩn chống tĩnh điện, bảo vệ hoá chất, phù hợp xưởng sơn và ngành hoá chất.",
      features: [["🛡️", "Công nghệ vải vi sợi FBS ProPlus Gard chắn hạt bụi thẩm thấu"], ["⚡", "Chống tĩnh điện (anti-static)"], ["🧪", "Bảo vệ khỏi dung môi và hoá chất"], ["🌬️", "Nhẹ, thoáng khí, phù hợp mặc cả ngày dài"]],
      specs: { "Công nghệ vải": "Micro-Fabric FBS ProPlus Gard", "Tính năng": "Chống tĩnh điện, chắn dung môi/hoá chất", "Kích cỡ": "M / L / XL / 2X", "Giá tham khảo (nguồn Mỹ)": "$80" },
      applications: ["Bảo hộ lao động xưởng sơn", "Ngành hoá chất, xử lý dung môi"],
      why: "Khác với đồ bảo hộ dùng một lần thông thường, chất liệu vi sợi cao cấp này vừa bảo vệ tốt vừa thoáng khí — phù hợp mặc liên tục nhiều giờ trong ca làm việc."
    },
    {
      slug: "gear-blue-gun-locker",
      name: "Tủ Đựng Súng Phun Sơn (Blue Gun Locker)",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "tools", subCatLabel: "Dụng cụ",
      img: "https://www.teamiwata.com/cdn/shop/files/PG-1A-A1_2M_large.png?v=1688567885",
      shortDesc: "Tủ thép sơn tĩnh điện chứa tới 24 súng phun, khoá số kết hợp khoá chìa, kích thước 20x30x12 inch.",
      lead: "Tủ đựng súng phun sơn chuyên dụng, được thiết kế riêng để bảo quản thiết bị phun sơn với nhiều loại giá đỡ phù hợp các dòng súng Anest Iwata khác nhau. Tủ chứa được tới 24 khẩu súng phun cùng không gian lưu trữ phụ kiện, làm từ thép cao cấp sơn tĩnh điện, khoá số kỹ thuật số kết hợp khoá chìa để bảo mật thiết bị.",
      features: [["🔫", "Chứa được tới 24 súng phun sơn"], ["🔐", "Khoá số kỹ thuật số kết hợp khoá chìa"], ["🏗️", "Thép cao cấp, sơn tĩnh điện"], ["📐", "Kích thước 20 x 30 x 12 inch, lắp treo tường"]],
      specs: { "Sức chứa": "Tối đa 24 súng phun", "Kích thước": "20 x 30 x 12 inch", "Chất liệu": "Thép sơn tĩnh điện", "Kiểu lắp đặt": "Treo tường", "Giá tham khảo (nguồn Mỹ)": "$800" },
      applications: ["Quản lý, bảo quản súng phun sơn tập trung", "Xưởng sơn có nhiều thiết bị cần bảo mật"],
      why: "Với xưởng sở hữu nhiều súng phun đắt tiền, một tủ chứa có khoá số giúp quản lý thiết bị gọn gàng và hạn chế thất lạc, mất cắp hiệu quả hơn để rời rạc."
    },
    {
      slug: "gear-product-catalog",
      name: "Catalogue Sản Phẩm Anest Iwata (Bản In)",
      category: "gear", categoryLabel: "Phụ Kiện & Quà Lưu Niệm",
      subCat: "tools", subCatLabel: "Dụng cụ",
      img: "https://www.teamiwata.com/cdn/shop/products/Catalog_Industrial-A1_large.jpg?v=1649693950",
      shortDesc: "Catalogue in đầy đủ toàn bộ sản phẩm Anest Iwata, sơ đồ cấu tạo và thông tin kỹ thuật.",
      lead: "Cuốn catalogue in đầy đủ giới thiệu toàn bộ sản phẩm Anest Iwata, kèm sơ đồ phân rã cấu tạo (part breakdown) và các thông tin kỹ thuật bổ sung — tài liệu tham khảo hữu ích cho đại lý và kỹ thuật viên.",
      features: [["📖", "Giới thiệu đầy đủ toàn bộ sản phẩm"], ["🔧", "Kèm sơ đồ phân rã cấu tạo (part breakdown)"], ["🚗", "Có bản riêng cho dòng ô tô (Auto Catalog)"]],
      specs: { "Định dạng": "Bản in giấy", "Phiên bản": "Full Catalog / Auto Catalog", "Giá tham khảo (nguồn Mỹ)": "$15" },
      applications: ["Tài liệu tham khảo cho đại lý, kỹ thuật viên", "Hỗ trợ tư vấn bán hàng"],
      why: "Một cuốn catalogue in tay vẫn hữu ích trong các buổi tư vấn trực tiếp tại xưởng, nơi không phải lúc nào cũng tiện tra cứu tài liệu điện tử."
    }
  ];
  window.PRODUCTS = (window.PRODUCTS || []).concat(list);
})();
